function slope = fit_slope(app,x,y,wdth,ratio,ins)

dx = range(wdth)/1000; dy = range(ratio)/1000;

xPartial = 	( ...
				point_prediction(x+dx/2,y,wdth,ratio,ins) - ...
				point_prediction(x-dx/2,y,wdth,ratio,ins) ...
			) / dx;

yPartial = 	( ...
				point_prediction(x,y+dy/2,wdth,ratio,ins) - ...
				point_prediction(x,y-dy/2,wdth,ratio,ins) ...
			) / (dy * app);
			
slope = sqrt(xPartial^2 + yPartial^2);
